### ISSUE TITLE
null pointer when building

### ISSUE THREAD

**Issue by jcompagner** [angelozerr/typescript.java#117]
I am using now the 1.2.0-snapshot version but building directly bombs out (over both my typescript projects)

java.lang.NullPointerException
	at ts.utils.VersionHelper.versionCompare(VersionHelper.java:30)
	at ts.utils.VersionHelper.canSupport(VersionHelper.java:9)
	at ts.client.CommandNames.canSupport(CommandNames.java:78)
	at ts.resources.TypeScriptProject.canSupport(TypeScriptProject.java:393)
	at ts.eclipse.ide.core.builder.TypeScriptBuilder.incrementalBuild(TypeScriptBuilder.java:133)
	at ts.eclipse.ide.core.builder.TypeScriptBuilder.build(TypeScriptBuilder.java:50)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by angelozerr** [comment]
I think it's because your TypeScript Runtime is not good. Select the well TypeScript Runtime in the preferences JavaScript / TypeScript / Runtime.

I must fix this problem in the https://github.com/angelozerr/typescript.java/issues/121

**Comment by angelozerr** [comment]
https://github.com/angelozerr/typescript.java/issues/121 should fix this issue.
