### ISSUE TITLE
using textmate for coloring results in an exception that the grammar can't be found

### ISSUE THREAD

**Issue by jcompagner** [angelozerr/typescript.java#118]
org.eclipse.textmate4e.core.TMException: Unknown location for grammar <source.ts>
	at org.eclipse.textmate4e.core.registry.Registry.loadGrammar(Registry.java:73)
	at org.eclipse.textmate4e.core.internal.grammars.GrammarRegistry.getGrammar(GrammarRegistry.java:28)
	at org.eclipse.textmate4e.core.internal.grammars.GrammarRegistryManager.getGrammarFor(GrammarRegistryManager.java:68)
	at org.eclipse.textmate4e.ui.text.TMPresentationReconciler$InternalListener.getGrammar(TMPresentationReconciler.java:219)
	at org.eclipse.textmate4e.ui.text.TMPresentationReconciler$InternalListener.inputDocumentChanged(TMPresentationReconciler.java:136)
	at org.eclipse.jface.text.TextViewer.fireInputDocumentChanged(TextViewer.java:2759)
	at org.eclipse.jface.text.TextViewer.setDocument(TextViewer.java:2800)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:634)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.setDocument(ProjectionViewer.java:365)
	at ts.eclipse.ide.jsdt.internal.ui.editor.TypeScriptSourceViewer.setDocument(TypeScriptSourceViewer.java:74)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:584)
	at org.eclipse.ui.texteditor.AbstractTextEditor.initializeSourceViewer(AbstractTextEditor.java:3995)
	at org.eclipse.ui.texteditor.AbstractTextEditor.createPartControl(AbstractTextEditor.java:3465)
	at org.eclipse.ui.texteditor.StatusTextEditor.createPartControl(StatusTextEditor.java:55)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.createPartControl(AbstractDecoratedTextEditor.java:445)
	at ts.eclipse.ide.jsdt.internal.ui.editor.JavaScriptLightWeightEditor.createPartControl(JavaScriptLightWeightEditor.java:148)
	at ts.eclipse.ide.jsdt.internal.ui.editor.TypeScriptEditor.createPartControl(TypeScriptEditor.java:323)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:150)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:99)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:340)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

**Comment by angelozerr** [comment]
Fixed with https://github.com/angelozerr/textmate.java/issues/25

@jcompagner please reinstall typescript.java. Thanks!
