### ISSUE TITLE
pressing the enter key in an editor results in an exception (and enter is not inserted)

### ISSUE THREAD

**Issue by jcompagner** [angelozerr/typescript.java#120]
java.lang.NullPointerException
	at ts.eclipse.ide.jsdt.internal.ui.editor.TypeScriptIndenter$CorePrefs.prefUseTabs(TypeScriptIndenter.java:167)
	at ts.eclipse.ide.jsdt.internal.ui.editor.TypeScriptIndenter$CorePrefs.<init>(TypeScriptIndenter.java:134)
	at ts.eclipse.ide.jsdt.internal.ui.editor.TypeScriptIndenter.<init>(TypeScriptIndenter.java:434)
	at ts.eclipse.ide.jsdt.internal.ui.editor.TypeScriptAutoIndentStrategy.smartIndentAfterNewLine(TypeScriptAutoIndentStrategy.java:275)
	at ts.eclipse.ide.jsdt.internal.ui.editor.TypeScriptAutoIndentStrategy.customizeDocumentCommand(TypeScriptAutoIndentStrategy.java:1221)
	at org.eclipse.jface.text.TextViewer.customizeDocumentCommand(TextViewer.java:3620)
	at org.eclipse.jface.text.TextViewer.handleVerifyEvent(TextViewer.java:3650)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.handleVerifyEvent(ProjectionViewer.java:1243)
	at org.eclipse.jface.text.TextViewer$TextVerifyListener.verifyText(TextViewer.java:431)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:274)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4410)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:802)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7342)
	at org.eclipse.swt.custom.StyledText.sendKeyEvent(StyledText.java:8225)
	at org.eclipse.swt.custom.StyledText.doContent(StyledText.java:2530)
	at org.eclipse.swt.custom.StyledText.handleKey(StyledText.java:6018)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6049)
	at org.eclipse.swt.custom.StyledText$7.handleEvent(StyledText.java:5733

i tried to play with the tab settings (project based or general)  but it didn't seem to matter.
(i do have don't convert tabs to spaces, i am in the "i love tab camp" ;) )

**Comment by angelozerr** [comment]
I think it's because your TypeScript Runtime is not good. Select the well TypeScript Runtime in the preferences JavaScript / TypeScript / Runtime.

I must fix this problem in the https://github.com/angelozerr/typescript.java/issues/121

**Comment by angelozerr** [comment]
https://github.com/angelozerr/typescript.java/issues/121 should fix this issue.
