### ISSUE TITLE
hoover over keywords is generating exceptions

### ISSUE THREAD

**Issue by jcompagner** [angelozerr/typescript.java#122]
this is in my log (when i have the communication tracing on):

TypeScript error#quickinfo with 1ms: 
java.util.concurrent.ExecutionException: ts.TypeScriptNoContentAvailableException: No content available.
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at ts.client.TypeScriptServiceClient.execute(TypeScriptServiceClient.java:375)
	at ts.client.TypeScriptServiceClient.quickInfo(TypeScriptServiceClient.java:217)
	at ts.resources.TypeScriptProject.quickInfo(TypeScriptProject.java:117)
	at ts.eclipse.ide.ui.hover.TypeScriptHover.getHoverInfo2(TypeScriptHover.java:56)
	at org.eclipse.wst.jsdt.internal.ui.text.java.hover.BestMatchHover.getHoverInfo2(BestMatchHover.java:149)
	at org.eclipse.wst.jsdt.internal.ui.text.java.hover.JavaEditorTextHoverProxy.getHoverInfo2(JavaEditorTextHoverProxy.java:81)
	at org.eclipse.jface.text.TextViewerHoverManager$4.run(TextViewerHoverManager.java:165)
Caused by: ts.TypeScriptNoContentAvailableException: No content available.
	at ts.internal.client.protocol.SimpleRequest.throwExceptionIfNeeded(SimpleRequest.java:73)
	at ts.internal.client.protocol.SimpleRequest.getResult(SimpleRequest.java:65)
	at ts.internal.client.protocol.SimpleRequest.getResult(SimpleRequest.java:1)
	at ts.internal.client.protocol.Request.call(Request.java:78)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

every time you hoover over a keyword (like function of var)

**Comment by angelozerr** [comment]
Yes it's a tsserver error log, so it's not a problem. I could filter this error but I prefer displaying the whole trace of tsserver.

**Comment by angelozerr** [comment]
@jcompagner can I close this issue?

**Comment by jcompagner** [comment]
fine by me, i was just wonder if we could do something with this (so not throwing that exception at all)
Exceptions are expensive and i think we already know that nothing comes in right?

**Comment by angelozerr** [comment]
@jcompagner when you say "in my log", it's in the standard Log view or tsserver console?

**Comment by jcompagner** [comment]
tsserver log (that you can check to see in the preferences)

**Comment by angelozerr** [comment]
Ok it should be fixed. Please tell me if it works.
