### ISSUE TITLE
ts.TypeScriptException: node file cannot be null

### ISSUE THREAD

**Issue by wolfgang-ch** [angelozerr/typescript.java#14]
I get this exception when running the TypeScriptEditor example, using Eclipse Mars.2 and the newest typescript.java

`ts.TypeScriptException: node file cannot be null
	at ts.nodejs.AbstractNodejsProcess.checkNodejsFile(AbstractNodejsProcess.java:66)
	at ts.nodejs.AbstractNodejsProcess.<init>(AbstractNodejsProcess.java:48)
	at ts.nodejs.NodejsProcess.<init>(NodejsProcess.java:39)
	at ts.nodejs.NodejsProcessManager.create(NodejsProcessManager.java:85)
	at ts.client.TypeScriptServiceClient.<init>(TypeScriptServiceClient.java:114)
	at ts.resources.TypeScriptProject.createServiceClient(TypeScriptProject.java:176)
	at ts.resources.TypeScriptProject.getClient(TypeScriptProject.java:136)
	at ts.eclipse.swt.samples.TypeScriptEditor.createUI(TypeScriptEditor.java:48)
	at ts.eclipse.swt.samples.TypeScriptEditor.main(TypeScriptEditor.java:36)`

**Comment by angelozerr** [comment]
@wolfgang-ch I have fixed the problem.Please note that this demo requires that you have installed node.js (it doesn't uses embeded node.js).

**Comment by wolfgang-ch** [comment]
great, now it works :+1:
