### ISSUE TITLE
Comparing ts files in git tree compare results in Nullpointer exception

### ISSUE THREAD

**Issue by danielvanmil** [angelozerr/typescript.java#180]
How to test:

- create a git a (local) git repo
- add a .ts file
- change the .ts file
- compare two versions of a file from the repo by selecting two versions from the history view
- an exception is thrown (see below)

This only applies to .ts files, so could/should be related to this plugin?
I'm using this feature a lot for code reviews etc.

Thanks.

org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4203)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3819)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
Caused by: java.lang.NullPointerException
	at ts.eclipse.ide.jsdt.internal.ui.compare.TypeScriptMergeViewer$1.getContentFormatter(TypeScriptMergeViewer.java:259)
	at org.eclipse.jface.text.source.SourceViewer.configure(SourceViewer.java:483)
	at org.eclipse.wst.jsdt.internal.ui.javaeditor.JavaSourceViewer.configure(JavaSourceViewer.java:209)
	at ts.eclipse.ide.jsdt.internal.ui.editor.TypeScriptSourceViewer.configure(TypeScriptSourceViewer.java:79)
	at ts.eclipse.ide.jsdt.internal.ui.compare.TypeScriptMergeViewer.configureTextViewer(TypeScriptMergeViewer.java:190)
	at org.eclipse.compare.contentmergeviewer.TextMergeViewer.configureSourceViewer(TextMergeViewer.java:3047)
	at org.eclipse.compare.contentmergeviewer.TextMergeViewer.updateContent(TextMergeViewer.java:2988)
	at org.eclipse.compare.contentmergeviewer.ContentMergeViewer.internalRefresh(ContentMergeViewer.java:788)
	at org.eclipse.compare.contentmergeviewer.ContentMergeViewer.inputChanged(ContentMergeViewer.java:688)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:286)
	at ts.eclipse.ide.jsdt.internal.ui.compare.TypeScriptMergeViewer.setInput(TypeScriptMergeViewer.java:144)
	at org.eclipse.compare.CompareViewerSwitchingPane.setInput(CompareViewerSwitchingPane.java:277)
	at org.eclipse.compare.internal.CompareContentViewerSwitchingPane.setInput(CompareContentViewerSwitchingPane.java:191)
	at org.eclipse.compare.CompareEditorInput.internalSetContentPaneInput(CompareEditorInput.java:845)
	at org.eclipse.compare.CompareEditorInput.access$7(CompareEditorInput.java:843)
	at org.eclipse.compare.CompareEditorInput$10.run(CompareEditorInput.java:779)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.compare.CompareEditorInput.feed1(CompareEditorInput.java:773)
	at org.eclipse.compare.CompareEditorInput.feedInput(CompareEditorInput.java:751)
	at org.eclipse.compare.CompareEditorInput.createContents(CompareEditorInput.java:555)
	at org.eclipse.compare.internal.CompareEditor.createCompareControl(CompareEditor.java:462)
	at org.eclipse.compare.internal.CompareEditor.access$6(CompareEditor.java:422)
	at org.eclipse.compare.internal.CompareEditor$1$1.run(CompareEditor.java:378)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:162)
	at org.eclipse.ui.internal.UISynchronizer$3.run(UISynchronizer.java:154)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	... 23 more

**Comment by angelozerr** [comment]
Once https://opensagres.ci.cloudbees.com/job/typescript.java/380/ job will be finished, please reinstall 1.3.0-SNAPSHOT and tell me if it fixes your problem. Thanks.

**Comment by danielvanmil** [comment]
works great!

**Comment by danielvanmil** [comment]
small issue is that the (TextMate) syntax coloring is not applied to ts file of the index.

**Comment by angelozerr** [comment]
@danielvanmil please create an other issue with TextMate problem. I have seen this problem but I think it's a minor problem. I'm very busy with CodeLens for the moment https://github.com/angelozerr/typescript.java/issues/181

I close this issue, please create a new issue. Thanks!
