### ISSUE TITLE
Editor could not be initialized when comparison is done

### ISSUE THREAD

**Issue by davidlecce** [angelozerr/typescript.java#217]
Eclipse Oxygen.1 (4.7.1)
TypeScript Core	1.4.0.201709191800

Plug-in: org.eclipse.ui.workbench.texteditor
Severity: Error
Message: Editor could not be initialized

`java.lang.NullPointerException
	at ts.eclipse.ide.ui.utils.EditorUtils.getResource(EditorUtils.java:137)
	at ts.eclipse.ide.ui.utils.EditorUtils.getResource(EditorUtils.java:133)
	at ts.eclipse.ide.jsdt.internal.ui.editor.TypeScriptSourceViewerConfiguration.getContentFormatter(TypeScriptSourceViewerConfiguration.java:175)
	at org.eclipse.jface.text.source.SourceViewer.configure(SourceViewer.java:483)
	at org.eclipse.wst.jsdt.internal.ui.javaeditor.JavaSourceViewer.configure(JavaSourceViewer.java:209)
	at ts.eclipse.ide.jsdt.internal.ui.editor.TypeScriptSourceViewer.configure(TypeScriptSourceViewer.java:79)
	at ts.eclipse.ide.jsdt.internal.ui.editor.JavaScriptLightWeightEditor.doSetInput(JavaScriptLightWeightEditor.java:199)
	at ts.eclipse.ide.jsdt.internal.ui.editor.TypeScriptEditor.doSetInput(TypeScriptEditor.java:1011)
	at ts.eclipse.ide.jsdt.internal.ui.compare.TypeScriptMergeViewer$TypeScriptEditorAdapter.doSetInput(TypeScriptMergeViewer.java:448)
	at org.eclipse.ui.texteditor.AbstractTextEditor$5.run(AbstractTextEditor.java:3154)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:437)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)
	at org.eclipse.ui.internal.WorkbenchWindow$14.run(WorkbenchWindow.java:2195)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2191)
	at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3172)
	at org.eclipse.ui.texteditor.AbstractTextEditor.init(AbstractTextEditor.java:3197)
	at ts.eclipse.ide.jsdt.internal.ui.compare.TypeScriptMergeViewer.getSourceViewerConfiguration(TypeScriptMergeViewer.java:266)
	at ts.eclipse.ide.jsdt.internal.ui.compare.TypeScriptMergeViewer.configureTextViewer(TypeScriptMergeViewer.java:193)
	at org.eclipse.compare.contentmergeviewer.TextMergeViewer.configureSourceViewer(TextMergeViewer.java:3080)
	at org.eclipse.compare.contentmergeviewer.TextMergeViewer.updateContent(TextMergeViewer.java:3028)
	at org.eclipse.compare.contentmergeviewer.ContentMergeViewer.internalRefresh(ContentMergeViewer.java:802)
	at org.eclipse.compare.contentmergeviewer.ContentMergeViewer.inputChanged(ContentMergeViewer.java:710)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:286)
	at ts.eclipse.ide.jsdt.internal.ui.compare.TypeScriptMergeViewer.setInput(TypeScriptMergeViewer.java:144)
	at org.eclipse.compare.CompareViewerSwitchingPane.setInput(CompareViewerSwitchingPane.java:270)
	at org.eclipse.compare.internal.CompareContentViewerSwitchingPane.setInput(CompareContentViewerSwitchingPane.java:192)
	at org.eclipse.compare.CompareEditorInput.internalSetContentPaneInput(CompareEditorInput.java:855)
	at org.eclipse.compare.CompareEditorInput.access$7(CompareEditorInput.java:853)
	at org.eclipse.compare.CompareEditorInput$10.run(CompareEditorInput.java:786)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.compare.CompareEditorInput.feed1(CompareEditorInput.java:779)
	at org.eclipse.compare.CompareEditorInput.feedInput(CompareEditorInput.java:757)
	at org.eclipse.compare.CompareEditorInput.createContents(CompareEditorInput.java:553)
	at org.eclipse.compare.internal.CompareEditor.createCompareControl(CompareEditor.java:444)
	at org.eclipse.compare.internal.CompareEditor.access$6(CompareEditor.java:404)
	at org.eclipse.compare.internal.CompareEditor$1$1.run(CompareEditor.java:361)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:58)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:168)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:150)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
`

**Comment by angelozerr** [comment]
Could you give me more info please how to produce this bug?

**Comment by davidlecce** [comment]
Sorry, I forgot to mention that it appears in the Error Log window when I use the compare editor.

**Comment by angelozerr** [comment]
That's strange it works for me? Which compare do you do?

**Comment by davidlecce** [comment]
The error appears on both "compare with -> each other" using two files, or "compare with -> head revision" using GIT

**Comment by davidlecce** [comment]
There is also an additional stack trace, unsure if it is helpful.

`org.eclipse.ui.PartInitException: Editor could not be initialized.
	at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3188)
	at org.eclipse.ui.texteditor.AbstractTextEditor.init(AbstractTextEditor.java:3197)
	at ts.eclipse.ide.jsdt.internal.ui.compare.TypeScriptMergeViewer.getSourceViewerConfiguration(TypeScriptMergeViewer.java:266)
	at ts.eclipse.ide.jsdt.internal.ui.compare.TypeScriptMergeViewer.configureTextViewer(TypeScriptMergeViewer.java:193)
	at org.eclipse.compare.contentmergeviewer.TextMergeViewer.configureSourceViewer(TextMergeViewer.java:3080)
	at org.eclipse.compare.contentmergeviewer.TextMergeViewer.updateContent(TextMergeViewer.java:3028)
	at org.eclipse.compare.contentmergeviewer.ContentMergeViewer.internalRefresh(ContentMergeViewer.java:802)
	at org.eclipse.compare.contentmergeviewer.ContentMergeViewer.inputChanged(ContentMergeViewer.java:710)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:286)
	at ts.eclipse.ide.jsdt.internal.ui.compare.TypeScriptMergeViewer.setInput(TypeScriptMergeViewer.java:144)
	at org.eclipse.compare.CompareViewerSwitchingPane.setInput(CompareViewerSwitchingPane.java:270)
	at org.eclipse.compare.internal.CompareContentViewerSwitchingPane.setInput(CompareContentViewerSwitchingPane.java:192)
	at org.eclipse.compare.CompareEditorInput.internalSetContentPaneInput(CompareEditorInput.java:855)
	at org.eclipse.compare.CompareEditorInput.access$7(CompareEditorInput.java:853)
	at org.eclipse.compare.CompareEditorInput$10.run(CompareEditorInput.java:786)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.compare.CompareEditorInput.feed1(CompareEditorInput.java:779)
	at org.eclipse.compare.CompareEditorInput.feedInput(CompareEditorInput.java:757)
	at org.eclipse.compare.CompareEditorInput.createContents(CompareEditorInput.java:553)
	at org.eclipse.compare.internal.CompareEditor.createCompareControl(CompareEditor.java:444)
	at org.eclipse.compare.internal.CompareEditor.access$6(CompareEditor.java:404)
	at org.eclipse.compare.internal.CompareEditor$1$1.run(CompareEditor.java:361)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:58)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:168)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:150)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: java.lang.NullPointerException
	at ts.eclipse.ide.ui.utils.EditorUtils.getResource(EditorUtils.java:137)
	at ts.eclipse.ide.ui.utils.EditorUtils.getResource(EditorUtils.java:133)
	at ts.eclipse.ide.jsdt.internal.ui.editor.TypeScriptSourceViewerConfiguration.getContentFormatter(TypeScriptSourceViewerConfiguration.java:175)
	at org.eclipse.jface.text.source.SourceViewer.configure(SourceViewer.java:483)
	at org.eclipse.wst.jsdt.internal.ui.javaeditor.JavaSourceViewer.configure(JavaSourceViewer.java:209)
	at ts.eclipse.ide.jsdt.internal.ui.editor.TypeScriptSourceViewer.configure(TypeScriptSourceViewer.java:79)
	at ts.eclipse.ide.jsdt.internal.ui.editor.JavaScriptLightWeightEditor.doSetInput(JavaScriptLightWeightEditor.java:199)
	at ts.eclipse.ide.jsdt.internal.ui.editor.TypeScriptEditor.doSetInput(TypeScriptEditor.java:1011)
	at ts.eclipse.ide.jsdt.internal.ui.compare.TypeScriptMergeViewer$TypeScriptEditorAdapter.doSetInput(TypeScriptMergeViewer.java:448)
	at org.eclipse.ui.texteditor.AbstractTextEditor$5.run(AbstractTextEditor.java:3154)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:437)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:353)
	at org.eclipse.ui.internal.WorkbenchWindow$14.run(WorkbenchWindow.java:2195)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2191)
	at org.eclipse.ui.texteditor.AbstractTextEditor.internalInit(AbstractTextEditor.java:3172)
	... 49 more
`
