### ISSUE TITLE
Eclipse Build Error

### ISSUE THREAD

**Issue by andymel123** [angelozerr/typescript.java#231]
I happened when I copied a function from another project (js) into my new ts project.
After replacing all "var" by "let" the error disappeared.

When I change a let back to var the error message starts again.

Here is the content of the Details page

```
Errors occurred during the build.
Errors running builder 'TypeScript Builder' on project 'BeachDefenseTS'.
Error while compiling with tsserver
java.util.concurrent.ExecutionException: ts.TypeScriptException: Error processing request. Debug Failure. 
Error: Debug Failure. 
    at typeToString (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:24720:22)
    at reportRelationError (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:30049:34)
    at isRelatedTo (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:30166:21)
    at typeArgumentsRelatedTo (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:30317:35)
    at structuredTypeRelatedTo (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:30455:38)
    at recursiveTypeRelatedTo (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:30366:53)
    at isRelatedTo (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:30153:38)
    at checkTypeRelatedTo (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:30032:26)
    at checkTypeAssignableTo (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:29772:20)
    at checkVariableLikeDeclaration (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:38367:21)
Error while compiling with tsserver
java.util.concurrent.ExecutionException: ts.TypeScriptException: Error processing request. Debug Failure. 
Error: Debug Failure. 
    at typeToString (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:24720:22)
    at reportRelationError (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:30049:34)
    at isRelatedTo (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:30166:21)
    at typeArgumentsRelatedTo (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:30317:35)
    at structuredTypeRelatedTo (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:30455:38)
    at recursiveTypeRelatedTo (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:30366:53)
    at isRelatedTo (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:30153:38)
    at checkTypeRelatedTo (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:30032:26)
    at checkTypeAssignableTo (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:29772:20)
    at checkVariableLikeDeclaration (E:\...\.metadata\.plugins\ts.repository\repositories\2.4.1\node_modules\typescript\lib\tsserver.js:38367:21)
```

**Comment by andymel123** [comment]
That var<=>let behavior described above was just some non-deterministic symptom I guess. The error still happened afterwards.

Changing the used typescript version from 2.4.1 to 2.3.3 did help. Now it works. 
Still there is some problem with version 2.4.1.

**Comment by angelozerr** [comment]
Please try to install last version of TypeScript 2.6.2 and retry it. It's a problem with TypeScript tsserver not with typescript.java
