### ISSUE TITLE
lint does not work with external typescript (sourcefile not in empty array)

### ISSUE THREAD

**Issue by nhnb** [angelozerr/typescript.java#245]
Linting works fine with the integrated typescript compiler. But after changing typescript->runtime to an external typescript installation (version 3.4.5), no lint errors are shown.

The typescript traces contains the error message "Error processing request. Could not find sourceFile ... in []". The filename and path is valid. I don't know where the empty array originates from.

~~~~
{
   "seq":0,
   "type":"response",
   "command":"semanticDiagnosticsSync",
   "request_seq":44,
   "success":false,
   "message":"Error processing request. Could not find sourceFile:
 '/home/me/workspace/frontend/src/app/app.component.ts' in [].
Error: Could not find sourceFile: '/home/me/workspace/frontend/src/app/app.component.ts' in [].
    at getValidSourceFile (/home/me/workspace/cs.sys.angularbase/node_modules/typescript/lib/tsserver.js:120714:23)
    at Object.getSemanticDiagnostics (/home/me/workspace/cs.sys.angularbase/node_modules/typescript/lib/tsserver.js:120916:36)
    at Object.proxy.getSemanticDiagnostics (/home/me/workspace/cs.sys.angularbase/node_modules/@angular/language-service/bundles/language-service.umd.js:49460:32)
    at /home/me/workspace/cs.sys.angularbase/node_modules/typescript/lib/tsserver.js:129601:140
    at IOSession.Session.getDiagnosticsWorker (/home/me/workspace/cs.sys.angularbase/node_modules/typescript/lib/tsserver.js:129443:35)
    at IOSession.Session.getSemanticDiagnosticsSync (/home/me/workspace/cs.sys.angularbase/node_modules/typescript/lib/tsserver.js:129601:29)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (/home/me/workspace/cs.sys.angularbase/node_modules/typescript/lib/tsserver.js:128961:61)
    at /home/me/workspace/cs.sys.angularbase/node_modules/typescript/lib/tsserver.js:130466:88
    at IOSession.Session.executeWithRequestId (/home/me/workspace/cs.sys.angularbase/node_modules/typescript/lib/tsserver.js:130457:28)
    at IOSession.Session.executeCommand (/home/me/workspace/cs.sys.angularbase/node_modules/typescript/lib/tsserver.js:130466:33)
    at IOSession.Session.onMessage (/home/me/workspace/cs.sys.angularbase/node_modules/typescript/lib/tsserver.js:130488:35)
    at Interface.<anonymous> (/home/me/workspace/cs.sys.angularbase/node_modules/typescript/lib/tsserver.js:131789:27)
    at Interface.emit (events.js:200:13)
    at Interface._onLine (readline.js:314:10)
    at Interface._normalWrite (readline.js:459:12)
    at Socket.ondata (readline.js:170:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)"
}
~~~~

- [Log with interal typescript](https://gist.github.com/nhnb/58711708847f93f5997b56c5026c7023)
- [Log with external trypescript](https://gist.github.com/nhnb/ca44964a4f47a4021e3bdb26c4f22a22)

**Comment by nhnb** [comment]
There are two issues:
- The tslint plugin was renamed from `tslint-language-service` to `typescript-tslint-plugin` which need to be updated in tsconfig.json
- The above error messages occurs if and only if `@angular/language-service` is enabled.

**Comment by angelozerr** [comment]
I'm sorry but i gave up this project. I suggest you that you move to wild
web developer which is based on language server protocol.

**Comment by jabby** [comment]
Here is some links about Eclipse Wild Web Developer

* [Github repository](https://github.com/eclipse/wildwebdeveloper/)
* [Marketplace entry](https://marketplace.eclipse.org/content/eclipse-wild-web-developer-web-development-eclipse-ide)

**Comment by angelozerr** [comment]
Thank's @jabby for your links. @nhnb please create issues in https://github.com/eclipse/wildwebdeveloper/issues to improve TypeScript support in Eclipse.
