### ISSUE TITLE
ClassCastException with Eclipse Neon M7 + Completion

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/typescript.java#56]
With Eclipse Neon M7, when completion is opened, there are 2 popup error

The first popup:
```
java.lang.ClassCastException: ts.eclipse.ide.jsdt.internal.ui.editor.contentassist.TypeScriptContentAssistInvocationContext cannot be cast to org.eclipse.wst.jsdt.ui.text.java.JavaContentAssistInvocationContext
	at org.eclipse.wst.jsdt.internal.ui.text.java.KeywordCompletionProposalComputer.computeCompletionProposals(KeywordCompletionProposalComputer.java:45)

```

The second popup

```
java.lang.ClassCastException: ts.eclipse.ide.jsdt.internal.ui.editor.contentassist.TypeScriptContentAssistInvocationContext cannot be cast to org.eclipse.wst.jsdt.ui.text.java.JavaContentAssistInvocationContext
	at org.eclipse.wst.jsdt.internal.ui.text.java.IdentifierCompletionProposalComputer.computeCompletionProposals(IdentifierCompletionProposalComputer.java:49)

```

**Comment by angelozerr** [comment]
This error comes from JSDT. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=493393

**Comment by angelozerr** [comment]
Bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=493393 was fixed.
