### ISSUE TITLE
ts.client.TypeScriptTimeoutException: Timeout error 10000000000ms

### ISSUE THREAD

**Issue by jalbr74** [angelozerr/typescript.java#82]
I'm not sure what I did, but I seem to have gotten myself into a bad state, and I'm not sure how to recover from it.  I've tried uninstalling and reinstalling the TypeScript plugins, but I still have the same problem.

The problem is my ts editor no longer shows red underlines for errors as I type, and the console spits out the following errors (I've enabled "Trace on console"):

```
TypeScript response#navbar with 1203747595ms: 
{"seq":0,"type":"response","command":"navbar","request_seq":115,"success":false,"message":"Error processing request. No Project.\nError: No Project.\n    at Errors (C:\\Users\\James\\Work\\projects-exercises\\2016-09-09\\my-app\\node_modules\\typescript\\lib\\tsserver.js:50743:32)\n    at ts.server.ts.server (C:\\Users\\James\\Work\\projects-exercises\\2016-09-09\\my-app\\node_modules\\typescript\\lib\\tsserver.js:50745:11)\n    at ts (C:\\Users\\James\\Work\\projects-exercises\\2016-09-09\\my-app\\node_modules\\typescript\\lib\\tsserver.js:51725:7)\n    at Object.<anonymous> (C:\\Users\\James\\Work\\projects-exercises\\2016-09-09\\my-app\\node_modules\\typescript\\lib\\tsserver.js:51726:3)\n    at Module._compile (module.js:556:32)\n    at Object.Module._extensions..js (module.js:565:10)\n    at Module.load (module.js:473:32)\n    at tryModuleLoad (module.js:432:12)\n    at Function.Module._load (module.js:424:3)\n    at Module.require (module.js:483:17)"}
-----------------------------------
TypeScript error#geterr with 10004ms: 
java.util.concurrent.ExecutionException: ts.client.TypeScriptTimeoutException: Timeout error 10000000000ms
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at ts.client.TypeScriptServiceClient.geterr(TypeScriptServiceClient.java:233)
	at ts.resources.TypeScriptProject.geterr(TypeScriptProject.java:131)
	at ts.eclipse.ide.validator.core.validation.TypeScriptValidationHelper.validate(TypeScriptValidationHelper.java:18)
	at ts.eclipse.ide.validator.internal.ui.validation.TypeScriptSourceValidator.validate(TypeScriptSourceValidator.java:63)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.validate(ReconcileStepForValidator.java:250)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.reconcileModel(ReconcileStepForValidator.java:208)
	at org.eclipse.jface.text.reconciler.AbstractReconcileStep.reconcile(AbstractReconcileStep.java:89)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ValidatorStrategy.reconcile(ValidatorStrategy.java:269)
	at org.eclipse.wst.jsdt.internal.ui.text.java.JavascriptValidationStrategy.reconcile(JavascriptValidationStrategy.java:101)
	at org.eclipse.wst.jsdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:85)
	at org.eclipse.wst.jsdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:103)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:73)
	at org.eclipse.wst.jsdt.internal.ui.text.JavaReconciler.process(JavaReconciler.java:374)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:207)
Caused by: ts.client.TypeScriptTimeoutException: Timeout error 10000000000ms
	at ts.internal.client.protocol.Request.call(Request.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Is there a way to blow away some kind of cache or something?  Like I said, I've reinstalled the plugins, and blown away and re-created my eclipse project, but I can't seem to get out of this state.  I'm afraid I'll have to reinstall eclipse or something.

Any troubleshooting steps you could provide would be appreciated.

Thanks!

**Comment by angelozerr** [comment]
It seems that you are using a custom TypeScript (perhaps 2.0.0?)

Perhaps you are using TypeScript 2.0.0? I know there are several issues https://github.com/Microsoft/TypeScript/search?utf8=%E2%9C%93&q=%22Error+processing+request.+No+Project%22&type=Issues

I suggest that you try with TypeScript 1.8.10 (have you the same problem?)

**Comment by jalbr74** [comment]
You are correct, I was using TypeScript 2.0.2.

I switched to the embedded 1.8.10, and the problem went away.  Thanks for the help getting to the bottom of this.  I'll keep playing with it to see if TypeScript 2.0.0 has this problem as well.

**Comment by angelozerr** [comment]
IMHO, you should wait for TypeScript 2.0.0 will b ereleased to use it.
